name: test
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: run test
    runs-on: ubuntu-latest
    steps:
      - run: docker run -p 9222:9222 -d zenika/alpine-chrome:122 --font-render-hinting=medium --hide-scrollbars --no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --single-process --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222
      - run: sleep 10s
      - run: docker ps -a
      - run: curl http://127.0.0.1:9222/json/version